import datetime
import structlog
from polyfactory.factories.pydantic_factory import ModelFactory

from product_agent.infrastructure.shopify.schemas import Fields, AllShopifyProducts

from product_agent.infrastructure.shopify.schemas import DraftResponse, DraftProduct
from product_agent.infrastructure.shopify.types import Inventory, Inputs, SkuSearchResponse, Product
from product_agent.infrastructure.shopify.exceptions import ShopifyError

logger = structlog.getLogger(__name__)

class MockShop:
    def __init__(self) -> None:
        pass

    def make_a_product_draft(self, shop_name: str, product_listing: DraftProduct) -> DraftResponse:
        logger.debug("Called: MockShop.make_a_product")
        if len(product_listing.variants) == 0:
            raise ShopifyError("No proposed variants")

        # Generate mock inventory item IDs for each variant
        variant_inventory_ids = [
            Inventory(
                inventory_item_id=f"mock_inventory_{i}",
                stores=[
                    Inputs(name_of_store="City", inventory_number=10),
                    Inputs(name_of_store="South Melbourne", inventory_number=10)
                ]
            )
            for i in range(len(product_listing.variants))
        ]

        logger.debug("MockShop.make_a_product returned DraftResponse")
        return DraftResponse(
            title=product_listing.title,
            id="mock_product_id_5327895723",
            variant_inventory_item_ids=variant_inventory_ids,
            url=f"https://admin.shopify.com/store/{shop_name}/products/5327895723",
            time_of_comepletion=datetime.datetime.now(),
            status_code=200,
        )

    def get_products_from_store(self, fields: Fields | None = None) -> list:
        """
        Mock getting products from your store
        
        Could build out some fakes manually and return them
        """

        class FakingShopifyProduct(ModelFactory):
            __model__ = AllShopifyProducts

        # Generated by a lib that inputs random data
        faked_by_faking_lib_result = FakingShopifyProduct.build()
        return faked_by_faking_lib_result.products

    def fill_inventory(self, inventory_data: Inventory):
        """Simulating filling stores inventory"""
        print("Inventory Filled")    
    
    async def search_by_sku(self, sku: int) -> SkuSearchResponse | None:
        """Mock search by SKU in your store"""
        # random rumber to simualte skus and test both returning a response and none
        if sku > 200:
            return None

        return SkuSearchResponse(
            sku=str(sku),
            product=Product(title="Optimum Nutrition Gold Standard Whey Protein")
        )
